version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME:
      KC_BOOTSTRAP_ADMIN_PASSWORD:
    ports:
      - "8080:8080"
    command:
      - start-dev
    networks:
      - library-network

  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-network

volumes:
  postgres_data:

networks:
  library-network:
    external: true