spring:
  application:
    name: LibraryAPI
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}
server:
  port: 8081

keycloak-initializer:
  initializeOnStartup: false
  masterRealm: ${KEYCLOAK_MASTER_REALM_NAME}
  applicationRealm: ${KEYCLOAK_APPLICATION_REALM_NAME}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
  client-id: ${KEYCLOAK_CLIENT_ID}
  username: ${KEYCLOAK_ADMIN_USERNAME}
  password: ${KEYCLOAK_ADMIN_PASSWORD}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  realm: ${KEYCLOAK_REALM}
  client-url: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/
  admin-url: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/auth
